### ISSUE TITLE
priv-1.10 images do not work

### ISSUE THREAD

**Issue by chrisguikema** [ucb-bar/fpga-images-zedboard#1]
Hello,

I am running on a zedboard using the 1.10 images. 

When I run the `hello` example, I get the following error:

```
root@zynq:~# ./fesvr-zynq pk hello
ERROR: No cores found
```

**Comment by freefreer** [comment]
Hi，
I encountered the same problem as chrisguikema.
I am running on a zedboard using the 1.10 images.

When I run the hello example, I get the following error:

root@zynq:~# ./fesvr-zynq pk hello
ERROR: No cores found

**Comment by bjfiedler** [comment]
Same problem here.
Revision 7b0028b works fine but 7e0080e shows error.

`root@zynq:~# ./fesvr-zynq pk hello`
`ERROR: No cores 
`

**Comment by zhemao** [comment]
Closing as duplicate, please follow the issue on fpga-zynq repo.

https://github.com/ucb-bar/fpga-zynq/issues/87
